name: test-and-deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and test and build
        run: |
          npm install
          npm test
          npm run build-for-gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist/picture-story
          CLEAN: true
